declare module "isomorphic-git"
declare module "@babel/core"
declare module "@babel/preset-react"
declare module "react-contextify"
declare module "unified"
declare module "v8n"
declare module "redux-logger"
declare module "rehype-react"
declare module "ini"
declare module "remark"
declare module "remark-parse"
declare module "remark-react"
declare module "uuid"
declare module "rimraf"
declare module "delay"
declare module "react-rte"
declare module "prettier/*"
declare module "diff3"
declare module "diff"
declare module "*.json"
declare module "*.css"
declare module "*.md"
declare module "enzyme-adapter-react-16"

declare var BrowserFS: any
declare var NEPlugins: { [pluginName: string]: any }
