declare var BrowserFS: any
declare module "isomorphic-git"
declare module "monaco-editor"
declare module "@storybook/addon-storyshots"
declare module "@babel/core"
declare module "@babel/preset-react"
declare module "react-contextify"
declare module "unified"
declare module "redux-logger"
declare module "rehype-react"
declare module "remark"
declare module "remark-parse"
declare module "remark-react"
declare module "@fortawesome/react-fontawesome"
declare module "@fortawesome/fontawesome"
declare module "@fortawesome/fontawesome-free-solid"
